name: Add or update a talk

on:
  issues:
    types: [labeled, edited]

jobs:
  validate-issue:
    name: Add a SC talk to the listing
    # Only run if approved
    if: |
      (contains(github.event.issue.labels.*.name, 'speakers_corner')
      || contains(github.event.issue.labels.*.name, 'lrc'))
      && contains(github.event.issue.labels.*.name, 'approved')
      && github.event.issue.state == 'open'
      && github.event.sender.login != 'vsf-bot'

    runs-on: ubuntu-latest
    
    steps :
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Install dependencies
        
        run: |
          python -m pip install --upgrade pip
          pip install -r bots/requirements.txt

      - name: Add data
        working-directory: ./bots
        run: python3 application_to_yaml.py
        env:
          VSF_BOT_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          
      - name: Schedule Zoom Talk
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.VSF_BOT_TOKEN }}
          repository: virtualscienceforum/automation
          event-type: schedule-zoom-talk
