name: Publish talk video

on:
  issue_comment:
    types: 
      - created

jobs:
  validate-issue:
    name: Publish the talk video
    # Only run if:
    # - Posted in the planning issue
    # - Seems like it has the right text
    # (The detailed check is on the receiving side)
    if: |
      (contains(github.event.issue.labels.*.name, 'speakers_corner')
      || contains(github.event.issue.labels.*.name, 'lrc'))
      && contains(github.event.issue.labels.*.name, 'approved')
      && contains(github.event.comment.body, 'approve')
      && contains(github.event.comment.body, 'publishing')
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    
    steps :

      - name: Trigger video publication
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.VSF_BOT_TOKEN }}
          repository: virtualscienceforum/automation
          event-type: publish-youtube-video
          client-payload: '{"issue": "${{ github.event.issue.number }}"}'
