name: Deploy website

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  schedule:
    - cron: '12 3 * * *'  # Rerender nightly

jobs:
  build-and-deploy:
    name: Render the talks and publish
    runs-on: ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and build
        run: |
          python -m pip install --upgrade pip
          if [ -f bots/requirements.txt ]; then pip install -r bots/requirements.txt; fi
          mkdocs build

      - name: Deploy PR preview
        run: |
          git fetch origin pages --depth=1
          git config user.name vsf-bot
          git config user.email vsfbot@antonakhmerov.org
          mike deploy pr-${{ github.event.pull_request.number }}
          git push https://$GITHUB_TOKEN@github.com/virtualscienceforum/virtualscienceforum.git pages
        if: | 
          github.event_name == 'pull_request' 
          && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
        env:
          GITHUB_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1.0.4
        with:
          message: "See the preview of the new version [here](https://virtualscienceforum.org/pr-${{ github.event.pull_request.number }}/)"
          GITHUB_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
        if: | 
          github.event_name == 'pull_request' && github.event.action == 'opened'

      - name: Undeploy PR preview
        run: |
          git fetch origin pages --depth=1
          git config user.name vsf-bot
          git config user.email vsfbot@antonakhmerov.org
          mike delete pr-${{ github.event.pull_request.number }}
          git push https://$GITHUB_TOKEN@github.com/virtualscienceforum/virtualscienceforum.git pages
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          GITHUB_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.ref == 'refs/heads/master'}}
        with:
          token: ${{ secrets.VSF_BOT_TOKEN }}
          branch: pages
          folder: site
          clean: true
          clean-exclude: |
            pr-*/
