name: Deploy website

on:
  push:
    branches:
      - master
  schedule:
    - cron: '12 3 * * *'  # Rerender nightly

jobs:
  build-and-deploy:
    name: Render the talks and publish
    runs-on: ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and build
        working-directory: ./bots
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 render_talks.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.VSF_BOT_TOKEN }}
          BRANCH: pages
          FOLDER: .
          CLEAN: true
          CLEAN-EXCLUDE: |
            pr-*/
