name: Deploy website

on:
  push:
  pull_request:
  schedule:
    - cron: '12 3 * * *'  # Rerender nightly

jobs:
  build-and-deploy:
    name: Render the talks and publish
    runs-on: ubuntu-latest

    steps :
      - name: Checkout code
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and build
        working-directory: ./bots
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          mkdocs build

      - name: Upload artifacfts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: site
          retention-days: 30
        if: ${{ github.event_name == 'pull_request' }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.ref == 'ref/head/master' }}
        with:
          token: ${{ secrets.VSF_BOT_TOKEN }}
          branch: pages
          folder: .
          clean: true
          clean-exclude: |
            pr-*/
