name: Publish speakers' corner video

on:
  issue_comment:
    types: 
      - created

jobs:
  validate-issue:
    name: Publish the talk video
    # Only run if:
    # - Posted in the speakers' corner issue
    # - By the issue creator
    # - Matches the response pattern
    if: |
      contains(github.event.issue.labels.*.name, 'speakers_corner')
      || contains(github.event.issue.labels.*.name, 'lrc')
      && contains(github.event.issue.labels.*.name, 'approved')
      && github.event.sender.login == github.event.issue.user.login
      && contains(github.event.comment.body, 'approve publishing')
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    
    steps :

      - name: Trigger video publication
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.VSF_BOT_TOKEN }}
          repository: virtualscienceforum/automation
          event-type: publish-youtube-video
          client-payload: '{"issue": "${{ github.event.issue.number }}"}'
